project_id = "bdriawoyrvnqzhvjcbah"

[functions.chat]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.telnyx-webhook]
verify_jwt = false

[functions.telnyx-webhook-failure]
verify_jwt = false

[functions.detect-frame]
verify_jwt = false
